# 使用说明 V3.2.0
# 1. 使用docker-compose  宿主机不需要配置host来发现
# 2. 无需修改源码，根目录  docker-compose up 即可
# 3. 静静等待服务启动

version: '2'
services:
  cloud-gateway:
    build:
      context: ./
      dockerfile: ./cloud-gateway/Dockerfile
    restart: always
    container_name: cloud-gateway
    image: cloud-gateway
    ports:
      - 9999:9999

  cloud-auth:
    build:
      context: ./
      dockerfile: ./cloud-auth/Dockerfile
    restart: always
    container_name: cloud-auth
    image: cloud-auth

  cloud-admin:
    build:
      context: ./
      dockerfile: ./cloud-admin/Dockerfile
    restart: always
    container_name: cloud-admin
    image: cloud-admin
